class_name Enums

enum unitTeam {NONE,PLAYER,ENEMY}

enum facingDirection {NONE,NORTH,NORTHEAST,EAST,SOUTHEAST,SOUTH,SOUTHWEST,WEST,NORTHWEST}

enum inventoryType {GROUND,BELT,BACKPACK,QUICKDRAW,RIGHTHAND,RIGHTLEG,LEFTHAND,LEFTLEG}
