class_name Enums

enum unitTeam {NONE,PLAYER,ENEMY, ANY}

enum facingDirection {NONE,NORTH,NORTHEAST,EAST,SOUTHEAST,SOUTH,SOUTHWEST,WEST,NORTHWEST}

enum inventoryType {GROUND,BELT,BACKPACK,QUICKDRAW,RIGHTHAND,RIGHTLEG,LEFTHAND,LEFTLEG,MOUSEHELD}

enum cellState {
	NONE = 0,
	AIR = 1 << 0,
	GROUND = 1 << 1,
	EMPTY = 1 << 2,
	OBSTRUCTED = 1 << 3,
	WALKABLE = 1 << 4 }


enum inventory_UI_slot_behavior {SELECT,EXECUTE_ACTION,TRY_TRANSFER}


enum UnitStance {
	NORMAL,
	CROUCHED
	}

enum UnitMovementStance {
	STATIONARY,
	MOVING
	}


enum FogState { UNSEEN, PREVIOUSLY_SEEN, VISIBLE }


enum ChangeTurnBehavior {NONE,MIN, MAX, INCREMENT, DERCREMENT }


enum DataLoadTiming {NONE, SCENESETUP, BEFOREEXECUTE, AFTEREXECUTE}


enum Stat {HEALTH, STAMINA, BRAVERY, TIMEUNITS}
